// <auto-generated />
namespace KJPFit.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class workoutupdated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(workoutupdated));
        
        string IMigrationMetadata.Id
        {
            get { return "202104160210011_workout updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
